# Generated by Django 6.0 on 2026-01-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingbillingaddress',
            name='order_notes',
        ),
        migrations.AddField(
            model_name='usercart',
            name='order_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
