# Generated by Django 6.0 on 2026-01-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=45)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='product-images')),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_fresh', models.BooleanField(default=False)),
                ('is_on_sales', models.BooleanField(default=False)),
                ('is_on_discount', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
